import CasinoImg from "@/assets/img/casinoimg.jpg";
import { ProjectType } from "../type";

export const projects: ProjectType[] = [
  {
    id: 0,
    img: CasinoImg,
    project: "PRJ_01",
    key: "prj_01",
    category: "web",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 1,
    img: CasinoImg,
    project: "PRJ_02",
    key: "prj_02",
    category: "e-commerce",
    technologies: ["Next.JS", "TypeScript", "Stripe", "SASS"],
  },
  {
    id: 2,
    img: CasinoImg,
    project: "PRJ_03",
    key: "prj_03",
    category: "game",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 3,
    img: CasinoImg,
    project: "PRJ_04",
    key: "prj_04",
    category: "creative",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 4,
    img: CasinoImg,
    project: "PRJ_05",
    key: "prj_05",
    category: "platform",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 5,
    img: CasinoImg,
    project: "PRJ_06",
    key: "prj_06",
    category: "web",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 6,
    img: CasinoImg,
    project: "PRJ_07",
    key: "prj_07",
    category: "game",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 7,
    img: CasinoImg,
    project: "PRJ_08",
    key: "prj_08",
    category: "creative",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 8,
    img: CasinoImg,
    project: "PRJ_09",
    key: "prj_09",
    category: "e-commerce",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 9,
    img: CasinoImg,
    project: "PRJ_10",
    key: "prj_10",
    category: "platform",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
  {
    id: 10,
    img: CasinoImg,
    project: "PRJ_11",
    key: "prj_11",
    category: "web",
    technologies: ["React", "TypeScript", "ChartJS", "TailwindCSS"],
  },
];
