import { ProjectTypes } from "./type";

export const allProjects: ProjectTypes[] = [
  {
    id: 1,
    url: "https://weather-next-app-amber.vercel.app/",
    src: "/img/weather-app.png",
    urlGitHub: "https://github.com/Giorgi014/Weather-Next-App",
    localUrl: "/home/projects/weather",
    title: "Weather App",
    stack: "Next.js Typescript",
    translationKey: "weatherApp",
    category: "informational",
  },
  {
    id: 2,
    url: "https://guess-my-number-chi-seven.vercel.app/",
    src: "/img/weather-app.png",
    urlGitHub: "https://github.com/Giorgi014/Guess-Number-ts",
    localUrl: "/home/projects/guessNumber",
    title: "Guess my Number",
    stack: "React.js Typescript",
    translationKey: "guessNumber",
    category: "game",
  },
  {
    id: 3,
    url: "https://guess-my-number-chi-seven.vercel.app/",
    src: "/img/weather-app.png",
    urlGitHub: "https://github.com/Giorgi014/Guess-Number-ts",
    localUrl: "/home/projects/guessNumber",
    title: "Guess my Number",
    stack: "React.js Typescript",
    translationKey: "guessNumber",
    category: "game",
  },
  {
    id: 4,
    url: "https://guess-my-number-chi-seven.vercel.app/",
    src: "/img/weather-app.png",
    urlGitHub: "https://github.com/Giorgi014/Guess-Number-ts",
    localUrl: "/home/projects/guessNumber",
    title: "Guess my Number",
    stack: "React.js Typescript",
    translationKey: "guessNumber",
    category: "game",
  },
  {
    id: 5,
    url: "https://guess-my-number-chi-seven.vercel.app/",
    src: "/img/weather-app.png",
    urlGitHub: "https://github.com/Giorgi014/Guess-Number-ts",
    localUrl: "/home/projects/guessNumber",
    title: "Guess my Number",
    stack: "React.js Typescript",
    translationKey: "guessNumber",
    category: "game",
  },
];
